<?php defined('_ENGINE') or die('Access Denied'); return array (
  0 => 'Activity',
  1 => 'Announcement',
  2 => 'Authorization',
  3 => 'Core',
  4 => 'Fields',
  5 => 'Group',
  6 => 'Invite',
  7 => 'Messages',
  8 => 'Network',
  9 => 'Payment',
  10 => 'ProfileCompleteness',
  11 => 'SocialConnect',
  12 => 'Socialbridge',
  13 => 'Storage',
  14 => 'User',
  15 => 'Ynresponsive1',
  16 => 'Ynresponsiveevent',
  17 => 'Ynvideo',
  18 => 'YounetCore',
); ?>