INSERT INTO `tarfee`.`engine4_user_locations` (`level`, `title`, `parent_id`, `continent`)VALUES 
('0', 'Algeria', '0', 'Africa'),
('0', 'Angola', '0', 'Africa'),
('0', 'Benin', '0', 'Africa'),
('0', 'Botswana', '0', 'Africa'),
('0', 'Burkina', '0', 'Africa'),
('0', 'Burundi', '0', 'Africa'),
('0', 'Cameroon', '0', 'Africa'),
('0', 'Cape Verde', '0', 'Africa'),
('0', 'Central African Republic', '0', 'Africa'),
('0', 'Chad', '0', 'Africa'),
('0', 'Comoros', '0', 'Africa'),
('0', 'Congo', '0', 'Africa'),
('0', 'Congo, Democratic Republic of', '0', 'Africa'),
('0', 'Djibouti', '0', 'Africa'),
('0', 'Egypt', '0', 'Africa'),
('0', 'Equatorial Guinea', '0', 'Africa'),
('0', 'Eritrea', '0', 'Africa'),
('0', 'Ethiopia', '0', 'Africa'),
('0', 'Gabon', '0', 'Africa'),
('0', 'Gambia', '0', 'Africa'),
('0', 'Ghana', '0', 'Africa'),
('0', 'Guinea', '0', 'Africa'),
('0', 'Guinea-Bissau', '0', 'Africa'),
('0', 'Ivory Coast', '0', 'Africa'),
('0', 'Kenya', '0', 'Africa'),
('0', 'Lesotho', '0', 'Africa'),
('0', 'Liberia', '0', 'Africa'),
('0', 'Libya', '0', 'Africa'),
('0', 'Madagascar', '0', 'Africa'),
('0', 'Malawi', '0', 'Africa'),
('0', 'Mali', '0', 'Africa'),
('0', 'Mauritania', '0', 'Africa'),
('0', 'Mauritius', '0', 'Africa'),
('0', 'Morocco', '0', 'Africa'),
('0', 'Mozambique', '0', 'Africa'),
('0', 'Namibia', '0', 'Africa'),
('0', 'Niger', '0', 'Africa'),
('0', 'Nigeria', '0', 'Africa'),
('0', 'Rwanda', '0', 'Africa'),
('0', 'Sao Tome and Principe', '0', 'Africa'),
('0', 'Senegal', '0', 'Africa'),
('0', 'Seychelles', '0', 'Africa'),
('0', 'Sierra Leone', '0', 'Africa'),
('0', 'Somalia', '0', 'Africa'),
('0', 'South Africa', '0', 'Africa'),
('0', 'South Sudan', '0', 'Africa'),
('0', 'Sudan', '0', 'Africa'),
('0', 'Swaziland', '0', 'Africa'),
('0', 'Tanzania', '0', 'Africa'),
('0', 'Togo', '0', 'Africa'),
('0', 'Tunisia', '0', 'Africa'),
('0', 'Uganda', '0', 'Africa'),
('0', 'Zambia', '0', 'Africa'),
('0', 'Zimbabwe', '0', 'Africa'),
('0', 'Afghanistan', '0', 'Asia'),
('0', 'Bahrain', '0', 'Asia'),
('0', 'Bangladesh', '0', 'Asia'),
('0', 'Bhutan', '0', 'Asia'),
('0', 'Brunei', '0', 'Asia'),
('0', 'Burma (Myanmar)', '0', 'Asia'),
('0', 'Cambodia', '0', 'Asia'),
('0', 'China', '0', 'Asia'),
('0', 'East Timor', '0', 'Asia'),
('0', 'India', '0', 'Asia'),
('0', 'Indonesia', '0', 'Asia'),
('0', 'Iran', '0', 'Asia'),
('0', 'Iraq', '0', 'Asia'),
('0', 'Israel', '0', 'Asia'),
('0', 'Japan', '0', 'Asia'),
('0', 'Jordan', '0', 'Asia'),
('0', 'Kazakhstan', '0', 'Asia'),
('0', 'Korea, North', '0', 'Asia'),
('0', 'Korea, South', '0', 'Asia'),
('0', 'Kuwait', '0', 'Asia'),
('0', 'Kyrgyzstan', '0', 'Asia'),
('0', 'Laos', '0', 'Asia'),
('0', 'Lebanon', '0', 'Asia'),
('0', 'Malaysia', '0', 'Asia'),
('0', 'Maldives', '0', 'Asia'),
('0', 'Mongolia', '0', 'Asia'),
('0', 'Nepal', '0', 'Asia'),
('0', 'Oman', '0', 'Asia'),
('0', 'Pakistan', '0', 'Asia'),
('0', 'Philippines', '0', 'Asia'),
('0', 'Qatar', '0', 'Asia'),
('0', 'Russian Federation', '0', 'Asia'),
('0', 'Saudi Arabia', '0', 'Asia'),
('0', 'Singapore', '0', 'Asia'),
('0', 'Sri Lanka', '0', 'Asia'),
('0', 'Syria', '0', 'Asia'),
('0', 'Tajikistan', '0', 'Asia'),
('0', 'Thailand', '0', 'Asia'),
('0', 'Turkey', '0', 'Asia'),
('0', 'Turkmenistan', '0', 'Asia'),
('0', 'United Arab Emirates', '0', 'Asia'),
('0', 'Uzbekistan', '0', 'Asia'),
('0', 'Vietnam', '0', 'Asia'),
('0', 'Yemen', '0', 'Asia'),
('0', 'Albania', '0', 'Europe'),
('0', 'Andorra', '0', 'Europe'),
('0', 'Armenia', '0', 'Europe'),
('0', 'Austria', '0', 'Europe'),
('0', 'Azerbaijan', '0', 'Europe'),
('0', 'Belarus', '0', 'Europe'),
('0', 'Belgium', '0', 'Europe'),
('0', 'Bosnia and Herzegovina', '0', 'Europe'),
('0', 'Bulgaria', '0', 'Europe'),
('0', 'Croatia', '0', 'Europe'),
('0', 'Cyprus', '0', 'Europe'),
('0', 'Czech Republic', '0', 'Europe'),
('0', 'Denmark', '0', 'Europe'),
('0', 'Estonia', '0', 'Europe'),
('0', 'Finland', '0', 'Europe'),
('0', 'France', '0', 'Europe'),
('0', 'Georgia', '0', 'Europe'),
('0', 'Germany', '0', 'Europe'),
('0', 'Greece', '0', 'Europe'),
('0', 'Hungary', '0', 'Europe'),
('0', 'Iceland', '0', 'Europe'),
('0', 'Ireland', '0', 'Europe'),
('0', 'Italy', '0', 'Europe'),
('0', 'Latvia', '0', 'Europe'),
('0', 'Liechtenstein', '0', 'Europe'),
('0', 'Lithuania', '0', 'Europe'),
('0', 'Luxembourg', '0', 'Europe'),
('0', 'Macedonia', '0', 'Europe'),
('0', 'Malta', '0', 'Europe'),
('0', 'Moldova', '0', 'Europe'),
('0', 'Monaco', '0', 'Europe'),
('0', 'Montenegro', '0', 'Europe'),
('0', 'Netherlands', '0', 'Europe'),
('0', 'Norway', '0', 'Europe'),
('0', 'Poland', '0', 'Europe'),
('0', 'Portugal', '0', 'Europe'),
('0', 'Romania', '0', 'Europe'),
('0', 'San Marino', '0', 'Europe'),
('0', 'Serbia', '0', 'Europe'),
('0', 'Slovakia', '0', 'Europe'),
('0', 'Slovenia', '0', 'Europe'),
('0', 'Spain', '0', 'Europe'),
('0', 'Sweden', '0', 'Europe'),
('0', 'Switzerland', '0', 'Europe'),
('0', 'Ukraine', '0', 'Europe'),
('0', 'United Kingdom', '0', 'Europe'),
('0', 'Vatican City', '0', 'Europe'),
('0', 'Antigua and Barbuda', '0', 'North America'),
('0', 'Bahamas', '0', 'North America'),
('0', 'Barbados', '0', 'North America'),
('0', 'Belize', '0', 'North America'),
('0', 'Canada', '0', 'North America'),
('0', 'Costa Rica', '0', 'North America'),
('0', 'Cuba', '0', 'North America'),
('0', 'Dominica', '0', 'North America'),
('0', 'Dominican Republic', '0', 'North America'),
('0', 'El Salvador', '0', 'North America'),
('0', 'Grenada', '0', 'North America'),
('0', 'Guatemala', '0', 'North America'),
('0', 'Haiti', '0', 'North America'),
('0', 'Honduras', '0', 'North America'),
('0', 'Jamaica', '0', 'North America'),
('0', 'Mexico', '0', 'North America'),
('0', 'Nicaragua', '0', 'North America'),
('0', 'Panama', '0', 'North America'),
('0', 'Saint Kitts and Nevis', '0', 'North America'),
('0', 'Saint Lucia', '0', 'North America'),
('0', 'Saint Vincent and the Grenadines', '0', 'North America'),
('0', 'Trinidad and Tobago', '0', 'North America'),
('0', 'United States', '0', 'North America'),
('0', 'Australia', '0', 'Oceania'),
('0', 'Fiji', '0', 'Oceania'),
('0', 'Kiribati', '0', 'Oceania'),
('0', 'Marshall Islands', '0', 'Oceania'),
('0', 'Micronesia', '0', 'Oceania'),
('0', 'Nauru', '0', 'Oceania'),
('0', 'New Zealand', '0', 'Oceania'),
('0', 'Palau', '0', 'Oceania'),
('0', 'Papua New Guinea', '0', 'Oceania'),
('0', 'Samoa', '0', 'Oceania'),
('0', 'Solomon Islands', '0', 'Oceania'),
('0', 'Tonga', '0', 'Oceania'),
('0', 'Tuvalu', '0', 'Oceania'),
('0', 'Vanuatu', '0', 'Oceania'),
('0', 'Argentina', '0', 'South America'),
('0', 'Bolivia', '0', 'South America'),
('0', 'Brazil', '0', 'South America'),
('0', 'Chile', '0', 'South America'),
('0', 'Colombia', '0', 'South America'),
('0', 'Ecuador', '0', 'South America'),
('0', 'Guyana', '0', 'South America'),
('0', 'Paraguay', '0', 'South America'),
('0', 'Peru', '0', 'South America'),
('0', 'Suriname', '0', 'South America'),
('0', 'Uruguay', '0', 'South America'),
('0', 'Venezuela', '0', 'South America');
